module nc4f_test_module
implicit none (type, external)

public :: test_type
public :: run_tests
public :: setup_test_results
private

type :: test_type
  character(len=:), allocatable :: name
  procedure(test_proc), nopass, pointer :: test => null()
  logical :: passed = .false.
end type test_type

interface
  subroutine test_proc(passed)
    !> Input/output argument(s): `passed`.
    logical, intent(inout) :: passed
  end subroutine test_proc
end interface

contains

!> Create the directory used for files generated by the test suite.
subroutine setup_test_results()
  integer :: exitstat

  call execute_command_line("mkdir -p build/test-results", exitstat=exitstat)
  if (exitstat /= 0) error stop &
    & "[setup_test_results] Cannot create build/test-results."
end subroutine setup_test_results

!> Execute `run_tests`.
subroutine run_tests(tests)
  !> Input/output argument(s): `tests(:)`.
  type(test_type), intent(inout) :: tests(:)
  integer :: i
  logical :: all_passed

  all_passed = .true.
  do i = 1, size(tests)
    tests(i)%passed = .false.
    call tests(i)%test(tests(i)%passed)
    if (tests(i)%passed) then
      print "(a)", "[test] "//tests(i)%name//": Passed."
    else
      print "(a)", "[test] "//tests(i)%name//": Failed."
      all_passed = .false.
    end if
  end do
  if (.not. all_passed) error stop "[test] >>> One or more tests failed. <<<"
  print "(a)", "[test] >>> All tests passed. <<<"
end subroutine run_tests

end module nc4f_test_module
