name = "netcdf.pack"
version = "0.0.1"
license = "MIT"
maintainer = "htang23@ncsu.edu"
author = "Han Tang"
copyright = "Copyright 2019-2025 Han Tang"
description = "NetCDF Fortran Library"
keywords = ["fortran", "modern-fortran", "NetCDF"]
homepage = "https://github.com/han190/netcdf.pack"

[build]
external-modules = ["netcdf"]
link = ["netcdf"]

[dependencies]
netcdf = "*"
# openmp = "*"

[library]
source-dir = "src"

[[test]]
name = "test"
source-dir = "test"
main = "test.f90"