name = "nc4f"
version = "0.0.1"
license = "MIT"
maintainer = "limpid.mazarine@gmail.com"
author = "Han Tang"
copyright = "Copyright 2019-2026 Han Tang"
description = "NetCDF Fortran Library"
keywords = ["fortran", "modern-fortran", "NetCDF"]
homepage = "https://github.com/han190/nc4f.pack"

[build]
# external-modules = "netcdf"
link = "netcdf"
auto-tests = false

[install]
library = true

[library]
source-dir = "src"

[[test]]
name = "test"
source-dir = "test"
main = "nc4f_test.f90"

[extra.fortitude.check]
ignore = ['C002', 'C071', 'C072', 'C121']
line-length = 120