site_name: nc4f
site_description: A modern Fortran interface to the NetCDF C library.
site_url: https://han190.github.io/nc4f.pack/
repo_url: https://github.com/han190/nc4f.pack
repo_name: han190/nc4f.pack

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Use dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Use light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - tables

nav:
  - Introduction: index.md
  - Examples: examples.md
  - API reference: api.md
  - Compatibility: compatibility.md
