name: nc4f
run-name: Testing nc4f by ${{ github.actor }}

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes gfortran libnetcdf-dev netcdf-bin pkg-config fypp

      - name: Report compiler
        run: gfortran --version

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Inspect generated NetCDF file
        run: ncdump -h build/test-results/characters.nc
