#: include "common.fypp"
interface extract
#: for K in kinds
  module procedure :: extract_att_${K}$_1d
  module procedure :: extract_att_${K}$_scalar
#: endfor
#: for K in kinds
#: for R in range(1, MAX_RANK+1)
  module procedure :: extract_var_${K}$_${R}$d
#: endfor
#: endfor
end interface extract

interface
#: for T, K in zip(types, kinds)
#: for R in range(1, MAX_RANK+1)
  #: if R == 1
  module subroutine extract_att_${K}$_${R}$d(att, ptr)
    type(attribute_type), target, intent(in) :: att
    ${T}$(${K}$), pointer, intent(out) :: ptr(:)
  end subroutine extract_att_${K}$_${R}$d${newline}$
  module subroutine extract_att_${K}$_scalar(att, ptr)
    type(attribute_type), target, intent(in) :: att
    ${T}$(${K}$), pointer, intent(out) :: ptr
  end subroutine extract_att_${K}$_scalar${newline}$
  #: endif
  module subroutine extract_var_${K}$_${R}$d(var, ptr)
    type(variable_type), target, intent(in) :: var
    ${T}$(${K}$), pointer, intent(out) :: ptr(${COLONS(R)}$)
  end subroutine extract_var_${K}$_${R}$d${newline}$
#: endfor
#: endfor
end interface
