#: include 'common.fypp'
#! ----------------------
#! Interface (data_array)
#! ----------------------
interface operator(.att.)
  #: for K in kinds
  module procedure :: new_att_${K}$
  module procedure :: new_att_${K}$_scalar
  #: endfor
  module procedure :: new_att_character
end interface operator(.att.)

#! ----------------
#! Module interface
#! ----------------
interface
  #: for T, K in zip(types, kinds)
  module function new_att_${K}$(name, values) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: values(:)
    type(attribute_type), target :: att
  end function new_att_${K}$${newline}$
  module function new_att_${K}$_scalar(name, value) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: value
    type(attribute_type), target :: att
  end function new_att_${K}$_scalar${newline}$
  #: endfor
  module function new_att_character(name, value) result(att)
    character(len=*), intent(in) :: name
    character(len=*), intent(in) :: value
    type(attribute_type), target :: att
  end function new_att_character
end interface