#: include "common.fypp"
interface extract
  #: for K in kinds
  module procedure :: extract_att_${K}$_vector
  module procedure :: extract_att_${K}$_scalar
  #: endfor
  module procedure :: extract_att_char_scalar
  module procedure :: extract_att_char_vector
  #: for K in kinds
  #: for R in range(1, MAX_RANK+1)
  module procedure :: extract_var_${K}$_${R}$d
  #: endfor
  #: endfor
end interface extract

interface
  #: for T, K in zip(types, kinds)
  module subroutine extract_att_${K}$_vector(att, ptr)
    type(attribute_type), target, intent(in) :: att
    ${T}$(${K}$), pointer, intent(out) :: ptr(:)
  end subroutine extract_att_${K}$_vector

  module subroutine extract_att_${K}$_scalar(att, ptr)
    type(attribute_type), target, intent(in) :: att
    ${T}$(${K}$), pointer, intent(out) :: ptr
  end subroutine extract_att_${K}$_scalar${NEWLINE(not (K == 'real64'))}$
  #: endfor

  module subroutine extract_att_char_vector(att, ptr)
    type(attribute_type), target, intent(in) :: att
    character, pointer, intent(out) :: ptr(:)
  end subroutine extract_att_char_vector

  module subroutine extract_att_char_scalar(att, ptr)
    type(attribute_type), target, intent(in) :: att
    character(len=:), pointer, intent(out) :: ptr
  end subroutine extract_att_char_scalar

  #: for T, K in zip(types, kinds)
  #: for R in range(1, MAX_RANK+1)
  module subroutine extract_var_${K}$_${R}$d(var, ptr)
    type(variable_type), target, intent(in) :: var
    ${T}$(${K}$), pointer, intent(out) :: ptr(${COLONS(R)}$)
  end subroutine extract_var_${K}$_${R}$d${NEWLINE(not (K == 'real64' and R == MAX_RANK))}$
  #: endfor
  #: endfor
end interface
