#: include "common.fypp"
#: for O, N in zip(ops, op_names)
interface operator(${O}$)
  module procedure :: ${N}$_vars
  #: for K in kinds
  module procedure :: ${N}$_var_${K}$
  module procedure :: ${N}$_${K}$_var
  #: endfor
end interface operator(${O}$) ${NEWLINE(not (N == 'pow'))}$
#: endfor

interface sum
  module procedure :: sum_vars
end interface sum

interface
  #: for N in op_names
  !> Apply operator `${N}$` element-wise to two variables.
  module function ${N}$_vars(x, y) result(res)
    !> Left-hand variable operand.
    type(variable_type), target, intent(in) :: x, y
    !> Resulting variable containing the element-wise result.
    type(variable_type), target :: res
  end function ${N}$_vars

  #: for T, K in zip(types, kinds)
  !> Apply operator `${N}$` between a variable and a scalar of kind `${K}$`.
  module function ${N}$_var_${K}$(x, y) result(res)
    !> Variable operand.
    type(variable_type), target, intent(in) :: x
    !> Scalar operand of type `${T}$` kind `${K}$`.
    ${T}$(${K}$), intent(in) :: y
    !> Resulting variable containing the element-wise result.
    type(variable_type), target :: res
  end function ${N}$_var_${K}$

  !> Apply operator `${N}$` between a scalar of kind `${K}$` and a variable.
  module function ${N}$_${K}$_var(x, y) result(res)
    !> Scalar left operand of type `${T}$` kind `${K}$`.
    ${T}$(${K}$), intent(in) :: x
    !> Variable right operand.
    type(variable_type), target, intent(in) :: y
    !> Resulting variable containing the element-wise result.
    type(variable_type), target :: res
  end function ${N}$_${K}$_var${NEWLINE(not (N == 'pow' and K == 'real64'))}$
  #: endfor
  #: endfor

  module function sum_vars(vars) result(s)
    type(variable_type), intent(in) :: vars(:)
    type(variable_type) :: s
  end function sum_vars
end interface

