#: include "common.fypp"
interface data_array
  #: for K in kinds
  #: for R in range(1, MAX_RANK+1)
  module procedure :: new_var_${K}$_${R}$d
  #: endfor
  #: endfor
end interface data_array

interface
  #: for T, K in zip(types, kinds)
  #: for R in range(1, MAX_RANK+1)
  !> Construct a `variable_type` of rank ${R}$ and kind ${K}$ from an array.
  module function new_var_${K}$_${R}$d(name, values, dims, atts) result(var)
    !> Name of the variable to create (will be trimmed).
    character(len=*), intent(in) :: name
    !> Array of values to populate the variable's data buffer.
    !> The array has rank ${R}$ and element type `${T}$` of kind `${K}$`.
    ${T}$(${K}$), intent(in) :: values(${COLONS(R)}$)
    !> Dimensions describing the variable's shape, ordered in Fortran order.
    type(dimension_type), intent(in) :: dims(:)
    !> Optional list of attributes to attach to the variable.
    type(attribute_type), intent(in), optional :: atts(:)
    !> Resulting `variable_type` initialized with metadata and buffer.
    type(variable_type) :: var
  end function new_var_${K}$_${R}$d${NEWLINE(not (K == 'real64' and R == MAX_RANK))}$
  #:endfor
#:endfor
end interface
