#: include "common.fypp"
submodule(nc4f_ds) nc4f_ds_attribute_constructor
implicit none (type, external)
contains

#: for D, T, K in zip(dtypes, types, kinds)
!> Create an `attribute_type` from an array of `${T}$` of kind `${K}$`.
pure module function new_att_${K}$(name, values) result(att)
  !> Name used to identify the NetCDF object.
  character(len=*), intent(in) :: name
  !> Values used to populate the attribute.
  ${T}$(${K}$), intent(in) :: values(:)
  !> Constructed attribute containing the supplied values.
  type(attribute_type) :: att

  call init_att(att, name, ${D}$, size(values, kind=int64))
  if (size(values) > 0) att%buffer = transfer(values, 0_int8, size(att%buffer))
end function new_att_${K}$

!> Create a scalar `attribute_type` from a `${T}$` value.
elemental module function new_att_${K}$_scalar(name, value) result(att)
  !> Name used to identify the NetCDF object.
  character(len=*), intent(in) :: name
  !> Scalar value stored in the attribute.
  ${T}$(${K}$), intent(in) :: value
  !> Constructed single-value attribute.
  type(attribute_type) :: att
  ${T}$(${K}$) :: tmp(1)

  tmp(1) = value
  att = new_att_${K}$(name, tmp)
end function new_att_${K}$_scalar${NEWLINE()}$
#: endfor

!> Create an `attribute_type` containing character data.
module function new_att_character(name, value) result(att)
  !> Name used to identify the NetCDF object.
  character(len=*), intent(in) :: name
  !> Character data stored in the attribute.
  character(len=*), intent(in) :: value
  !> Constructed attribute containing the character data.
  type(attribute_type) :: att

  call init_att(att, name, CHAR_TYPE, len(value, kind=int64))
  if (len(value) > 0) att%buffer = transfer(value, 0_int8, size(att%buffer))
end function new_att_character

end submodule nc4f_ds_attribute_constructor
