#: include "common.fypp"
interface operator(.att.)
  #: for K in kinds
  module procedure :: new_att_${K}$
  module procedure :: new_att_${K}$_scalar
  #: endfor
  module procedure :: new_att_character
end interface operator(.att.)

interface
  #: for T, K in zip(types, kinds)
  !> Create an `attribute_type` from an array of `${T}$` of kind `${K}$`.
  pure module function new_att_${K}$(name, values) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: values(:)
    type(attribute_type) :: att
  end function new_att_${K}$

  !> Create a scalar `attribute_type` from a `${T}$` value.
  elemental module function new_att_${K}$_scalar(name, value) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: value
    type(attribute_type) :: att
  end function new_att_${K}$_scalar${NEWLINE(not (K == 'real64'))}$
  #: endfor

  !> Create an `attribute_type` containing character data.
  module function new_att_character(name, value) result(att)
    character(len=*), intent(in) :: name
    character(len=*), intent(in) :: value
    type(attribute_type), target :: att
  end function new_att_character
end interface
