#: include 'common.fypp'
interface operator(.att.)
  #: for K in kinds
  module procedure :: new_att_${K}$
  module procedure :: new_att_${K}$_scalar
  #: endfor
  module procedure :: new_att_character
end interface operator(.att.)

interface
  #: for T, K in zip(types, kinds)
  module function new_att_${K}$(name, values) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: values(:)
    type(attribute_type) :: att
  end function new_att_${K}$

  module function new_att_${K}$_scalar(name, value) result(att)
    character(len=*), intent(in) :: name
    ${T}$(${K}$), intent(in) :: value
    type(attribute_type) :: att
  end function new_att_${K}$_scalar${NEWLINE(not (K == 'real64'))}$
  #: endfor

  module function new_att_character(name, value) result(att)
    character(len=*), intent(in) :: name, value
    type(attribute_type), target :: att
  end function new_att_character
end interface
