#: include 'common.fypp'
submodule(nc4f) nc4f_variable_constructor
implicit none (type, external)
contains

#: for N, T, K, C in zip(nc_types, types, kinds, ckinds)
#: for R in range(1, MAX_RANK+1)
!> Construct a `variable_type` of rank ${R}$ and kind ${K}$ from an array.
module function new_var_${K}$_${R}$d(name, values, dims, atts) result(var)
  !> Name of the variable to create (will be trimmed).
  character(len=*), intent(in) :: name
  !> Array of values to populate the variable's data buffer.
  !> The array has rank ${R}$ and element type `${T}$` of kind `${K}$`.
  ${T}$(${K}$), intent(in) :: values(${COLONS(R)}$)
  !> Dimensions describing the variable's shape, ordered in Fortran order.
  type(dimension_type), intent(in) :: dims(:)
  !> Optional list of attributes to attach to the variable.
  type(attribute_type), intent(in), optional :: atts(:)
  !> Resulting `variable_type` initialized with metadata and buffer.
  type(variable_type) :: var
  !> Pointer view into the variable's internal buffer with matching type
  !> and rank. Used to copy the input `values` efficiently into `var`.
  ${T}$(${C}$), pointer :: var_ptr(${COLONS(R)}$)

  call allocate_variable(var, name, ${N}$, size(values, kind=int64), dims, atts)
  call extract(var, var_ptr)
  var_ptr = values
end function new_var_${K}$_${R}$d${NEWLINE()}$
#: endfor
#: endfor
end submodule nc4f_variable_constructor
