#: include 'common.fypp'
submodule(module_netcdf) submodule_extract
implicit none (type, external)
contains

#: for T, K in zip(types + ['char'], kinds + ['char'])
#: for R in ('vector', 'scalar')
module subroutine extract_att_${K}$_${R}$(att, ptr)
  type(attribute_type), target, intent(in) :: att
  #: if K == 'char' and R == 'scalar'
  character(len=:), pointer, intent(out) :: ptr
  #: elif K == 'char' and R == 'vector'
  character, pointer, intent(out) :: ptr(:)
  #: elif R == 'vector'
  ${T}$(${K}$), pointer, intent(out) :: ptr(:)
  #: elif R == 'scalar'
  ${T}$(${K}$), pointer, intent(out) :: ptr
  #: endif
  #: if (K == 'char' and R == 'scalar')
  character, pointer :: ptrs(:)
  integer :: i
  #: else
  type(c_ptr) :: cptr
  #: endif

  #: if R == 'scalar' and T != 'char'
  if (att%len /= 1) error stop &
    & "[extract_att_${K}$_scalar] Not a scalar."
  #: endif
  #: if K == 'char' and R == 'scalar'
  call extract_att_char_vector(att, ptrs)
  do i = 1, size(ptrs)
    ptr(i:i) = ptrs(i)
  end do
  #: elif R == 'vector'
  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, ptr, [att%len])
  #: elif R == 'scalar'
  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, ptr)
  #: endif
end subroutine extract_att_${K}$_${R}$${NEWLINE(not (K == 'char' and R == 'scalar'))}$
#: endfor
#: endfor

#: for T, K in zip(types, kinds)
#: for R in range(1, MAX_RANK+1)
module subroutine extract_var_${K}$_${R}$d(var, ptr)
  type(variable_type), target, intent(in) :: var
  ${T}$(${K}$), pointer, intent(out) :: ptr(${COLONS(R)}$)
  type(c_ptr) :: cptr

  associate (rank_ptr => rank(ptr))
    if (rank_ptr > 1 .and. rank_ptr /= size(shape(var))) error stop &
      & "[extract_var_${K}$_${R}$d] Invalid rank."
  end associate
  if (nc2kind(var%dtype) /= kind(ptr)) error stop &
    & "[extract_var_${K}$_${R}$d] Invalid kind."

  cptr = c_loc(var%buffer(1))
  #: if R == 1
  call c_f_pointer(cptr, ptr, [var%len])
  #: else
  call c_f_pointer(cptr, ptr, shape(var))
  #: endif
end subroutine extract_var_${K}$_${R}$d${NEWLINE(not (K == 'real64' and R == MAX_RANK))}$
#: endfor
#: endfor

pure function nc2kind(nc_type) result(kind_val)
  integer(c_int), intent(in) :: nc_type
  integer :: kind_val

  select case (nc_type)
  case (NC_NAT)
    error stop "[nc2kind] Not a type."
  case (NC_BYTE)
    kind_val = kind(0_int8)
  case (NC_CHAR)
    kind_val = kind('')
  case (NC_SHORT)
    kind_val = kind(0_int16)
  case (NC_INT)
    kind_val = kind(0_int32)
  case (NC_FLOAT)
    kind_val = kind(0._real32)
  case (NC_DOUBLE)
    kind_val = kind(0._real64)
  case (NC_INT64)
    kind_val = kind(0._int64)
  case default
    error stop "[nc2kind] Unsupported type."
  end select
end function nc2kind

end submodule submodule_extract
