#: include 'common.fypp'
submodule(module_netcdf) submodule_arithmetic
implicit none (type, external)
contains

#: for O, N in zip(ops, op_names)
module function ${N}$_vars(x, y) result(res)
  type(variable_type), target, intent(in) :: x, y
  type(variable_type), target :: res

  if (any(x%dims /= y%dims)) &
    & error stop "[add_vars] Unequal dims."
  if (x%dtype /= y%dtype) &
    & error stop "[add_vars] Unequal data type."

  call allocate_variable(res, mold=x)
  select case (x%dtype)
    #: for C, T, K in zip(nc_types, types, kinds)
  case (${C}$)
    block
      ${T}$(${K}$), pointer :: xp(:), yp(:), resp(:)
      type(c_ptr) :: cptr

      cptr = c_loc(res%buffer(1))
      call c_f_pointer(cptr, resp, [res%len])
      cptr = c_loc(x%buffer(1))
      call c_f_pointer(cptr, xp, [x%len])
      cptr = c_loc(y%buffer(1))
      call c_f_pointer(cptr, yp, [y%len])
      resp = xp ${O}$ yp
      nullify (xp, yp, resp)
    end block
    #: endfor
  end select
end function ${N}$_vars${newline}$
#: for C1, T1, K1 in zip(nc_types, types, kinds)
module function ${N}$_var_${K1}$(x, y) result(res)
  type(variable_type), target, intent(in) :: x
  ${T1}$(${K1}$), intent(in) :: y
  type(variable_type), target :: res
  ${T1}$(${K1}$), pointer :: xp(:), resp(:)
  type(c_ptr) :: cptr

  if (x%dtype /= ${C1}$) error stop &
    & "[${N}$_var_${K1}$] typeof(x) /= typeof(y)."

  call allocate_variable(res, mold=x)
  cptr = c_loc(res%buffer(1))
  call c_f_pointer(cptr, resp, [res%len])
  cptr = c_loc(x%buffer(1))
  call c_f_pointer(cptr, xp, [x%len])
  resp = xp ${O}$ y
end function ${N}$_var_${K1}$

module function ${N}$_${K1}$_var(x, y) result(res)
  ${T1}$(${K1}$), intent(in) :: x
  type(variable_type), target, intent(in) :: y
  type(variable_type), target :: res
  ${T1}$(${K1}$), pointer :: yp(:), resp(:)
  type(c_ptr) :: cptr

  if (y%dtype /= ${C1}$) error stop &
    & "[${N}$_var_${K1}$] typeof(x) /= typeof(y)."

  call allocate_variable(res, mold=y)
  cptr = c_loc(res%buffer(1))
  call c_f_pointer(cptr, resp, [res%len])
  cptr = c_loc(y%buffer(1))
  call c_f_pointer(cptr, yp, [y%len])
  resp = x ${O}$ yp
end function ${N}$_${K1}$_var${newline}$
#: endfor
#: endfor
module function sum_vars(vars) result(s)
  type(variable_type), intent(in) :: vars(:)
  type(variable_type) :: s
  integer :: i

  select case (size(vars))
  case (1)
    s = vars(1)
  case (2)
    s = vars(1) + vars(2)
  case (3:)
    s = vars(1)
    do i = 2, size(vars)
      s = s + vars(i)
    end do
  case default
    error stop "[sum_vars] Invalid size."
  end select
end function sum_vars

end submodule submodule_arithmetic${newline}$
