#: include 'common.fypp'
submodule(module_netcdf) submodule_variable_constructor
implicit none (type, external)
contains${newline}$
#: for N, T, K, C in zip(nc_types, types, kinds, ckinds)
#: for R in range(1, MAX_RANK+1)
module function new_var_${K}$_${R}$d(name, values, dims, atts) result(var)
  character(len=*), intent(in) :: name
  ${T}$(${K}$), target, intent(in) :: values(${COLONS(R)}$)
  type(dimension_type), intent(in) :: dims(:)
  type(attribute_type), intent(in), optional :: atts(:)
  type(variable_type), target :: var
  ${T}$(${C}$), pointer :: var_ptr(${COLONS(R)}$)


  if (present(atts)) then
    call allocate_variable(var, name, ${N}$, &
      & size(values, kind=int64), dims, atts)
  else
    call allocate_variable(var, name, ${N}$, &
      & size(values, kind=int64), dims)
  end if

  call extract(var, var_ptr)
  var_ptr = values
  nullify (var_ptr)
end function new_var_${K}$_${R}$d${newline}$
#: endfor
#: endfor
end submodule submodule_variable_constructor