#: include 'common.fypp'
submodule(module_netcdf) submodule_arithmetic
implicit none (type, external)
contains${newline}$
#: for O, N in zip(ops, op_names)
module function ${N}$_vars(x, y) result(res)
  type(variable_type), target, intent(in) :: x, y
  type(variable_type), target :: res

  if (any(x%dims /= y%dims)) &
    & error stop "[add_vars] Unequal dims."
  if (x%dtype /= y%dtype) &
    & error stop "[add_vars] Unequal data type."

  res%name = x%name
  res%dtype = x%dtype
  res%len = x%len
  res%dims = x%dims
  res%atts = x%atts

  select case (x%dtype)
  #: for C, T, K in zip(nc_types, types, kinds)
  case (${C}$)
    block
      ${T}$(${K}$), pointer :: xp(:), yp(:), resp(:)
      type(c_ptr) :: cptr

      call allocate_buffer(res)
      cptr = c_loc(res%buffer(1))
      call c_f_pointer(cptr, resp, [res%len])
      cptr = c_loc(x%buffer(1))
      call c_f_pointer(cptr, xp, [x%len])
      cptr = c_loc(y%buffer(1))
      call c_f_pointer(cptr, yp, [y%len])
      resp = xp ${O}$ yp
      nullify (xp, yp, resp)
    end block
  #: endfor
  end select
end function ${N}$_vars${newline}$
#: for I1, C1, T1, K1 in zip(indices, nc_types, types, kinds)
module function ${N}$_var_${K1}$(x, y) result(res)
  type(variable_type), target, intent(in) :: x
  ${T1}$(${K1}$), intent(in) :: y
  type(variable_type), target :: res

  res%name = x%name
  res%len = x%len
  res%dims = x%dims
  res%atts = x%atts

  select case (x%dtype)
  #: for I, C, T, K in zip(indices, nc_types, types, kinds)
  case (${C}$)
    block
      #: set T_SEL = COMPARE_TYPES1(I1, I)
      #: set K_SEL = COMPARE_TYPES2(I1, I)
      ${T}$(${K}$), pointer :: xp(:)
      ${T_SEL}$(${K_SEL}$), pointer :: resp(:)
      type(c_ptr) :: cptr

      #: set TYPE_SEL = COMPARE_TYPES3(I1, I)
      res%dtype = ${TYPE_SEL}$
      call allocate_buffer(res)
      cptr = c_loc(res%buffer(1))
      call c_f_pointer(cptr, resp, [res%len])
      cptr = c_loc(x%buffer(1))
      call c_f_pointer(cptr, xp, [x%len])
      #: set RESULT = COMPARE_TYPES4(I1, I)
      #: if RESULT == '1'
      resp = xp ${O}$ y
      #: else
      resp = xp
      resp = resp ${O}$ y
      #: endif
      nullify (xp, resp)
    end block
  #: endfor
  end select
end function ${N}$_var_${K1}$${newline}$
module function ${N}$_${K1}$_var(x, y) result(res)
  ${T1}$(${K1}$), intent(in) :: x
  type(variable_type), target, intent(in) :: y
  type(variable_type), target :: res

  res%name = y%name
  res%len = y%len
  res%dims = y%dims
  res%atts = y%atts

  select case (y%dtype)
  #: for I, C, T, K in zip(indices, nc_types, types, kinds)
  case (${C}$)
    block
      #: set T_SEL = COMPARE_TYPES1(I1, I)
      #: set K_SEL = COMPARE_TYPES2(I1, I)
      ${T}$(${K}$), pointer :: yp(:)
      ${T_SEL}$(${K_SEL}$), pointer :: resp(:)
      type(c_ptr) :: cptr

      #: set TYPE_SEL = COMPARE_TYPES3(I1, I)
      call allocate_buffer(res)
      cptr = c_loc(res%buffer(1))
      call c_f_pointer(cptr, resp, [res%len])
      cptr = c_loc(y%buffer(1))
      call c_f_pointer(cptr, yp, [y%len])
      #: set RESULT = COMPARE_TYPES4(I1, I)
      #: if RESULT == '1'
      resp = x ${O}$ yp
      #: else
      resp = x
      resp = resp ${O}$ yp
      #: endif
      nullify (yp, resp)
    end block
  #: endfor
  end select
end function ${N}$_${K1}$_var${newline}$
#: endfor
#: endfor
module function sum_vars(vars) result(s)
  type(variable_type), intent(in) :: vars(:)
  type(variable_type) :: s
  integer :: i

  select case (size(vars))
  case (1)
    s = vars(1)
  case (2)
    s = vars(1) + vars(2)
  case (3:)
    s = vars(1)
    do i = 2, size(vars)
      s = s + vars(i)
    end do
  case default
    error stop "[sum_vars] Invalid size."
  end select
end function sum_vars${newline}$
end submodule submodule_arithmetic${newline}$