#: include 'common.fypp'
submodule(module_netcdf) submodule_extract
implicit none (type, external)
contains

#: for T, K in zip(types, kinds)
module subroutine extract_att_${K}$_vector(att, ptr)
  type(attribute_type), target, intent(in) :: att
  ${T}$(${K}$), pointer, intent(out) :: ptr(:)
  type(c_ptr) :: cptr

  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, ptr, [att%len])
end subroutine extract_att_${K}$_vector

module subroutine extract_att_${K}$_scalar(att, ptr)
  type(attribute_type), target, intent(in) :: att
  ${T}$(${K}$), pointer, intent(out) :: ptr
  type(c_ptr) :: cptr

  if (att%len /= 1) error stop &
    & "[extract_att_${K}$_scalar] Not a scalar."
  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, ptr)
end subroutine extract_att_${K}$_scalar

#: endfor
module subroutine extract_att_char_vector(att, ptr)
  type(attribute_type), target, intent(in) :: att
  character, pointer, intent(out) :: ptr(:)
  type(c_ptr) :: cptr

  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, ptr, [att%len])
end subroutine extract_att_char_vector

module subroutine extract_att_char_scalar(att, ptr)
  type(attribute_type), target, intent(in) :: att
  character(len=:), pointer, intent(out) :: ptr
  character, pointer :: ptrs(:)
  integer :: i

  call extract_att_char_vector(att, ptrs)
  do i = 1, size(ptrs)
    ptr(i:i) = ptrs(i)
  end do
end subroutine extract_att_char_scalar

#: for T, K in zip(types, kinds)
#: for R in range(1, MAX_RANK+1)
module subroutine extract_var_${K}$_${R}$d(var, ptr)
  type(variable_type), target, intent(in) :: var
  ${T}$(${K}$), pointer, intent(out) :: ptr(${COLONS(R)}$)
  type(c_ptr) :: cptr

  if (rank(ptr) /= size(shape(var))) error stop &
    & "[extract_var_${K}$_${R}$d] Invalid rank."
  cptr = c_loc(var%buffer(1))
  call c_f_pointer(cptr, ptr, shape(var))
end subroutine extract_var_${K}$_${R}$d

#: endfor
#: endfor
end submodule submodule_extract
