#: include "common.fypp"
submodule(module_netcdf) submodule_attribute_constructor
implicit none (type, external)
contains${newline}$
#: for C, T, K, CK in zip(nc_types, types, kinds, ckinds)
module function new_att_${K}$(name, values) result(att)
  character(len=*), intent(in) :: name
  ${T}$(${K}$), intent(in) :: values(:)
  type(attribute_type), target :: att
  ${T}$(${K}$), pointer :: ptr(:)

  call new_att_(att, name, ${C}$, size(values, kind=int64))
  call allocate_buffer(att)
  call extract(att, ptr)
  ptr = values
  nullify (ptr)
end function new_att_${K}$${newline}$
module function new_att_${K}$_scalar(name, value) result(att)
  character(len=*), intent(in) :: name
  ${T}$(${K}$), intent(in) :: value
  type(attribute_type), target :: att
  ${T}$(${K}$) :: tmp(1)

  tmp(1) = value
  att = new_att_${K}$(name, tmp)
end function new_att_${K}$_scalar${newline}$
#: endfor
module function new_att_character(name, value) result(att)
  character(len=*), intent(in) :: name
  character(len=*), intent(in) :: value
  type(attribute_type), target :: att
  character(kind=c_char), pointer :: fptr(:)
  type(c_ptr) :: cptr
  integer(int64) :: i

  call new_att_(att, name, NC_CHAR, len(value, kind=int64))
  call allocate_buffer(att)
  cptr = c_loc(att%buffer(1))
  call c_f_pointer(cptr, fptr, [att%len])
  do i = 1, att%len
    fptr(i) = value(i:i)
  end do
  nullify (fptr)
end function new_att_character

pure subroutine new_att_(att, name, dtype, len)
  type(attribute_type), intent(inout) :: att
  character(len=*), intent(in) :: name
  integer(int32), intent(in) :: dtype
  integer(int64), intent(in) :: len

  att%name = trim(adjustl(name))
  att%dtype = dtype
  att%len = len
end subroutine new_att_

end submodule submodule_attribute_constructor